In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/train.csv")

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Male,Urban,Sedan,No,Yes,Medium,No
668661,668661,32,129990.0,5.0,2,5,4,1.0,Female,Suburban,SUV,Yes,Yes,Low,No
668662,668662,64,121791.0,24.2,1,5,6,1.0,Female,Suburban,Hatchback,Yes,Yes,Low,No
668663,668663,51,115923.0,43.7,2,0,0,1.0,Female,Rural,SUV,Yes,Yes,Low,No
668664,668664,54,68986.0,5.0,1,6,9,2.0,Male,Urban,Hatchback,No,Yes,Low,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668665 entries, 0 to 668664
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           668665 non-null  int64
 1   Age                          668665 non-null  int64
 2   Annual_Income_USD            668665 non-null  float64
 3   Daily_Commute_km             668665 non-null  float64
 4   Number_of_Cars_Owned         668665 non-null  int64
 5   Charging_Stations_Near_Home  668665 non-null  int64
 6   Charging_Stations_Near_Work  668665 non-null  int64
 7   Environmental_Concern_Level  668665 non-null  float64
 8   Gender                       668665 non-null  object
 9   City_Type                    668665 non-null  object
 10  Current_Car_Type             668665 non-null  object
 11  Home_Charging_Possible       668665 non-null  object
 12  Subsidy_Available            668665 non-null  object
 13  Range_Anxiety_Level          668665 non-null  object
 14  Will_Buy_EV                  668665 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 76.5+ MB

In [ ]:
df.describe()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,668665.00000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000
mean,334332.00000,47.039171,84769.266989,32.158298,1.712626,4.960408,7.176314,2.935477
std,193027.10321,12.875448,28648.029042,18.730474,0.729275,3.926843,5.186627,1.429119
min,0.00000,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,167166.00000,36.000000,67376.000000,17.200000,1.000000,2.000000,3.000000,2.000000
50%,334332.00000,47.000000,84880.000000,33.600000,2.000000,4.000000,6.000000,3.000000
75%,501498.00000,58.000000,102753.000000,47.400000,2.000000,7.000000,10.000000,4.000000
max,668664.00000,69.000000,188549.000000,98.700000,4.000000,14.000000,19.000000,5.000000

In [ ]:
df.isnull().sum()

id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
Will_Buy_EV                    0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668665 entries, 0 to 668664
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           668665 non-null  int64
 1   Age                          668665 non-null  int64
 2   Annual_Income_USD            668665 non-null  float64
 3   Daily_Commute_km             668665 non-null  float64
 4   Number_of_Cars_Owned         668665 non-null  int64
 5   Charging_Stations_Near_Home  668665 non-null  int64
 6   Charging_Stations_Near_Work  668665 non-null  int64
 7   Environmental_Concern_Level  668665 non-null  float64
 8   Gender                       668665 non-null  object
 9   City_Type                    668665 non-null  object
 10  Current_Car_Type             668665 non-null  object
 11  Home_Charging_Possible       668665 non-null  object
 12  Subsidy_Available            668665 non-null  object
 13  Range_Anxiety_Level          668665 non-null  object
 14  Will_Buy_EV                  668665 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 76.5+ MB

In [ ]:
df = pd.get_dummies(df, columns=['Gender'] , drop_first=True)

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other
0,0,66,92887.0,23.4,2,3,7,1.0,Suburban,Sedan,Yes,No,Low,No,True,False
1,1,38,30000.0,5.0,1,2,2,4.0,Rural,SUV,Yes,No,Low,No,True,False
2,2,26,94389.0,36.8,1,8,15,5.0,Urban,Sedan,No,Yes,Low,Yes,False,False
3,3,66,73580.0,23.7,2,6,9,3.0,Suburban,Hatchback,Yes,No,Low,No,True,False
4,4,54,57898.0,50.8,1,2,3,3.0,Suburban,Hatchback,Yes,No,Low,No,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Urban,Sedan,No,Yes,Medium,No,True,False
668661,668661,32,129990.0,5.0,2,5,4,1.0,Suburban,SUV,Yes,Yes,Low,No,False,False
668662,668662,64,121791.0,24.2,1,5,6,1.0,Suburban,Hatchback,Yes,Yes,Low,No,False,False
668663,668663,51,115923.0,43.7,2,0,0,1.0,Rural,SUV,Yes,Yes,Low,No,False,False
668664,668664,54,68986.0,5.0,1,6,9,2.0,Urban,Hatchback,No,Yes,Low,No,True,False

In [ ]:
df['Gender_Male'] = df['Gender_Male'].astype(int)

In [ ]:
df['Gender_Other'] = df["Gender_Other"].astype(int)

In [ ]:
df.loc[df['Will_Buy_EV'] == 'Yes', 'Will_Buy_EV'] = True
df.loc[df['Will_Buy_EV'] == 'No', 'Will_Buy_EV'] = False

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other
0,0,66,92887.0,23.4,2,3,7,1.0,Suburban,Sedan,Yes,No,Low,False,1,0
1,1,38,30000.0,5.0,1,2,2,4.0,Rural,SUV,Yes,No,Low,False,1,0
2,2,26,94389.0,36.8,1,8,15,5.0,Urban,Sedan,No,Yes,Low,True,0,0
3,3,66,73580.0,23.7,2,6,9,3.0,Suburban,Hatchback,Yes,No,Low,False,1,0
4,4,54,57898.0,50.8,1,2,3,3.0,Suburban,Hatchback,Yes,No,Low,False,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Urban,Sedan,No,Yes,Medium,False,1,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,Suburban,SUV,Yes,Yes,Low,False,0,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,Suburban,Hatchback,Yes,Yes,Low,False,0,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,Rural,SUV,Yes,Yes,Low,False,0,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,Urban,Hatchback,No,Yes,Low,False,1,0

In [ ]:
df.loc[df['Home_Charging_Possible'] == 'Yes', 'Home_Charging_Possible'] = True
df.loc[df['Home_Charging_Possible'] == 'No', 'Home_Charging_Possible'] = False

In [ ]:
df.loc[df['Subsidy_Available']== 'Yes', 'Subsidy_Available'] = True
df.loc[df['Subsidy_Available']== 'No', 'Subsidy_Available'] = False

In [ ]:
df['Home_Charging_Possible'] = df["Home_Charging_Possible"].astype(int)

In [ ]:
df["Subsidy_Available"] = df["Subsidy_Available"].astype(int)
df["Will_Buy_EV"] = df["Will_Buy_EV"].astype(int)

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other
0,0,66,92887.0,23.4,2,3,7,1.0,Suburban,Sedan,1,0,Low,0,1,0
1,1,38,30000.0,5.0,1,2,2,4.0,Rural,SUV,1,0,Low,0,1,0
2,2,26,94389.0,36.8,1,8,15,5.0,Urban,Sedan,0,1,Low,1,0,0
3,3,66,73580.0,23.7,2,6,9,3.0,Suburban,Hatchback,1,0,Low,0,1,0
4,4,54,57898.0,50.8,1,2,3,3.0,Suburban,Hatchback,1,0,Low,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Urban,Sedan,0,1,Medium,0,1,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,Suburban,SUV,1,1,Low,0,0,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,Suburban,Hatchback,1,1,Low,0,0,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,Rural,SUV,1,1,Low,0,0,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,Urban,Hatchback,0,1,Low,0,1,0

In [ ]:
df.loc[df["Range_Anxiety_Level"] == "Low", "Range_Anxiety_Level"] = 0
df.loc[df["Range_Anxiety_Level"] == "Medium", "Range_Anxiety_Level"] = 1
df.loc[df["Range_Anxiety_Level"] == "High", "Range_Anxiety_Level"] = 2

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other
0,0,66,92887.0,23.4,2,3,7,1.0,Suburban,Sedan,1,0,0,0,1,0
1,1,38,30000.0,5.0,1,2,2,4.0,Rural,SUV,1,0,0,0,1,0
2,2,26,94389.0,36.8,1,8,15,5.0,Urban,Sedan,0,1,0,1,0,0
3,3,66,73580.0,23.7,2,6,9,3.0,Suburban,Hatchback,1,0,0,0,1,0
4,4,54,57898.0,50.8,1,2,3,3.0,Suburban,Hatchback,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Urban,Sedan,0,1,1,0,1,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,Suburban,SUV,1,1,0,0,0,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,Suburban,Hatchback,1,1,0,0,0,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,Rural,SUV,1,1,0,0,0,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,Urban,Hatchback,0,1,0,0,1,0

In [ ]:
df = pd.get_dummies(df,columns=["Current_Car_Type"] , drop_first=True)

In [ ]:
df = pd.get_dummies(df,columns=["City_Type"] , drop_first=True)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
df["Age"] = scaler.fit_transform(df[["Age"]])
df['Annual_Income_USD'] = scaler.fit_transform(df[["Annual_Income_USD"]])
df['Daily_Commute_km'] = scaler.fit_transform(df[["Daily_Commute_km"]])

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,City_Type_Suburban,City_Type_Urban
0,0,1.472427,0.283593,-0.467772,2,3,7,1.0,1,0,0,0,1,0,False,True,False,True,False
1,1,-0.702214,-1.911282,-1.450082,1,2,2,4.0,1,0,0,0,1,0,True,False,False,False,False
2,2,-1.634203,0.336016,0.247606,1,8,15,5.0,0,1,0,1,0,0,False,True,False,False,True
3,3,1.472427,-0.390258,-0.451756,2,6,9,3.0,1,0,0,0,1,0,False,False,False,True,False
4,4,0.540438,-0.937589,0.995016,1,2,3,3.0,1,0,0,0,1,0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658697,658697,-1.168209,1.406631,-0.062035,2,7,7,5.0,1,1,0,1,1,0,True,False,False,True,False
658698,658698,0.851101,-0.727061,2.009358,2,11,12,3.0,0,1,1,0,1,0,False,True,False,False,True
658699,658699,0.928767,-0.329843,1.817167,2,6,5,3.0,0,1,1,0,1,0,False,True,False,False,True
658700,658700,-0.935211,-1.590150,-0.094067,1,3,5,1.0,1,0,0,0,0,0,False,True,False,True,False
658701,658701,0.618104,-0.548224,1.993342,2,9,11,2.0,0,0,0,0,0,0,False,True,False,False,True

In [ ]:
df['Number_of_Cars_Owned'] = scaler.fit_transform(df[["Number_of_Cars_Owned"]])
df['Charging_Stations_Near_Home'] = scaler.fit_transform(df[["Charging_Stations_Near_Home"]])
df['Charging_Stations_Near_Work'] = scaler.fit_transform(df[["Charging_Stations_Near_Work"]])

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,City_Type_Suburban,City_Type_Urban
0,0,1.472427,0.283593,-0.467772,0.393982,-0.499017,-0.033715,1.0,1,0,0,0,1,0,False,True,False,True,False
1,1,-0.702214,-1.911282,-1.450082,-0.977076,-0.753652,-0.997862,4.0,1,0,0,0,1,0,True,False,False,False,False
2,2,-1.634203,0.336016,0.247606,-0.977076,0.774158,1.508920,5.0,0,1,0,1,0,0,False,True,False,False,True
3,3,1.472427,-0.390258,-0.451756,0.393982,0.264888,0.351944,3.0,1,0,0,0,1,0,False,False,False,True,False
4,4,0.540438,-0.937589,0.995016,-0.977076,-0.753652,-0.805033,3.0,1,0,0,0,1,0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658697,658697,-1.168209,1.406631,-0.062035,0.393982,0.519523,-0.033715,5.0,1,1,0,1,1,0,True,False,False,True,False
658698,658698,0.851101,-0.727061,2.009358,0.393982,1.538062,0.930432,3.0,0,1,1,0,1,0,False,True,False,False,True
658699,658699,0.928767,-0.329843,1.817167,0.393982,0.264888,-0.419374,3.0,0,1,1,0,1,0,False,True,False,False,True
658700,658700,-0.935211,-1.590150,-0.094067,-0.977076,-0.499017,-0.419374,1.0,1,0,0,0,0,0,False,True,False,True,False
658701,658701,0.618104,-0.548224,1.993342,0.393982,1.028792,0.737602,2.0,0,0,0,0,0,0,False,True,False,False,True

In [ ]:
df['Current_Car_Type_SUV'] = df["Current_Car_Type_SUV"].astype(int)
df['Current_Car_Type_Sedan'] = df["Current_Car_Type_Sedan"].astype(int)
df['Current_Car_Type_Truck'] = df["Current_Car_Type_Truck"].astype(int)
df['City_Type_Suburban'] = df["City_Type_Suburban"].astype(int)
df['City_Type_Urban'] = df["City_Type_Urban"].astype(int)
df["Range_Anxiety_Level"] = df["Range_Anxiety_Level"].astype(int)

In [ ]:
df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV,Gender_Male,Gender_Other,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,City_Type_Suburban,City_Type_Urban
0,0,1.472427,0.283593,-0.467772,0.393982,-0.499017,-0.033715,1.0,1,0,0,0,1,0,0,1,0,1,0
1,1,-0.702214,-1.911282,-1.450082,-0.977076,-0.753652,-0.997862,4.0,1,0,0,0,1,0,1,0,0,0,0
2,2,-1.634203,0.336016,0.247606,-0.977076,0.774158,1.508920,5.0,0,1,0,1,0,0,0,1,0,0,1
3,3,1.472427,-0.390258,-0.451756,0.393982,0.264888,0.351944,3.0,1,0,0,0,1,0,0,0,0,1,0
4,4,0.540438,-0.937589,0.995016,-0.977076,-0.753652,-0.805033,3.0,1,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658697,658697,-1.168209,1.406631,-0.062035,0.393982,0.519523,-0.033715,5.0,1,1,0,1,1,0,1,0,0,1,0
658698,658698,0.851101,-0.727061,2.009358,0.393982,1.538062,0.930432,3.0,0,1,1,0,1,0,0,1,0,0,1
658699,658699,0.928767,-0.329843,1.817167,0.393982,0.264888,-0.419374,3.0,0,1,1,0,1,0,0,1,0,0,1
658700,658700,-0.935211,-1.590150,-0.094067,-0.977076,-0.499017,-0.419374,1.0,1,0,0,0,0,0,0,1,0,1,0
658701,658701,0.618104,-0.548224,1.993342,0.393982,1.028792,0.737602,2.0,0,0,0,0,0,0,0,1,0,0,1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.drop(["Will_Buy_EV","id"],axis=1)
y = df["Will_Buy_EV"]

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

In [ ]:
logistic_model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
y_pred = logistic_model.predict(x_test)

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.94    108657
           1       0.71      0.65      0.68     23084

    accuracy                           0.89    131741
   macro avg       0.82      0.80      0.81    131741
weighted avg       0.89      0.89      0.89    131741

In [ ]:
confusion_matrix(y_test,y_pred)

array([[102600,   6057],
       [  8087,  14997]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
tree_model = DecisionTreeClassifier(max_depth=8)

In [ ]:
tree_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=8)

In [ ]:
tree_pred = tree_model.predict(x_test)
print(classification_report(y_test,tree_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94    108657
           1       0.72      0.65      0.68     23084

    accuracy                           0.89    131741
   macro avg       0.82      0.80      0.81    131741
weighted avg       0.89      0.89      0.89    131741

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()

In [ ]:
nb_model.fit(x_train,y_train)

GaussianNB()

In [ ]:
nb_model_pred = nb_model.predict(x_test)
print(classification_report(y_test,nb_model_pred))

              precision    recall  f1-score   support

           0       0.98      0.82      0.89    108657
           1       0.52      0.91      0.66     23084

    accuracy                           0.84    131741
   macro avg       0.75      0.86      0.77    131741
weighted avg       0.90      0.84      0.85    131741

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=25)

In [ ]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=25)

In [ ]:
knn_model_pred = knn_model.predict(x_test)

In [ ]:
print(accuracy_score(y_test,knn_model_pred))

0.8897654281291828

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100)

In [ ]:
rf_model.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
rf_model_pred = rf_model.predict(x_test)
print(classification_report(y_test,rf_model_pred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93    108657
           1       0.71      0.64      0.68     23084

    accuracy                           0.89    131741
   macro avg       0.82      0.79      0.81    131741
weighted avg       0.89      0.89      0.89    131741

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ada_model = AdaBoostClassifier(n_estimators=100)

In [ ]:
ada_model.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
ada_model_pred = ada_model.predict(x_test)
print(classification_report(y_test,ada_model_pred))

              precision    recall  f1-score   support

           0       0.92      0.95      0.94    108657
           1       0.72      0.63      0.67     23084

    accuracy                           0.89    131741
   macro avg       0.82      0.79      0.81    131741
weighted avg       0.89      0.89      0.89    131741

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(n_estimators=150)

In [ ]:
gb_model.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=150)

In [ ]:
gb_model_pred = gb_model.predict(x_test)
print(classification_report(y_test,gb_model_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94    108657
           1       0.73      0.65      0.69     23084

    accuracy                           0.90    131741
   macro avg       0.83      0.80      0.81    131741
weighted avg       0.89      0.90      0.89    131741

In [ ]:
from sklearn.ensemble import VotingClassifier

In [ ]:
voting_model = VotingClassifier(estimators=[('logistic',logistic_model),('tree',tree_model),('nb',nb_model),('knn',knn_model),('rf',rf_model),('ada',ada_model),('gb',gb_model)],voting='hard')

In [ ]:
voting_model.fit(x_train,y_train)

VotingClassifier(estimators=[('logistic', LogisticRegression()),
                             ('tree', DecisionTreeClassifier(max_depth=8)),
                             ('nb', GaussianNB()),
                             ('knn', KNeighborsClassifier(n_neighbors=25)),
                             ('rf', RandomForestClassifier()),
                             ('ada', AdaBoostClassifier(n_estimators=100)),
                             ('gb',
                              GradientBoostingClassifier(n_estimators=150))])

In [ ]:
voting_model_pred = voting_model.predict(x_test)
print(classification_report(y_test,voting_model_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94    110375
           1       0.72      0.65      0.69     23358

    accuracy                           0.90    133733
   macro avg       0.83      0.80      0.81    133733
weighted avg       0.89      0.90      0.89    133733

In [ ]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier(n_estimators=100 , learning_rate=0.1 , max_depth=5 , random_state=42 , objective='binary:logistic' , eval_metric='logloss')

In [ ]:
xgb_model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
xgb_model_pred = xgb_model.predict(x_test)
print(classification_report(y_test,xgb_model_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94    110375
           1       0.73      0.66      0.69     23358

    accuracy                           0.90    133733
   macro avg       0.83      0.80      0.81    133733
weighted avg       0.89      0.90      0.89    133733

In [ ]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
bag_model = BaggingClassifier(n_estimators=200,random_state=42,max_samples=0.8,max_features=0.8,oob_score=True,bootstrap=True,bootstrap_features=True,n_jobs=-1,verbose=1)

In [ ]:
bag_model.fit(x_train,y_train)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:  6.9min finished

BaggingClassifier(bootstrap_features=True, max_features=0.8, max_samples=0.8,
                  n_estimators=200, n_jobs=-1, oob_score=True, random_state=42,
                  verbose=1)

In [ ]:
bag_model_pred = bag_model.predict(x_test)
print(classification_report(y_test,bag_model_pred))

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    9.6s finished

              precision    recall  f1-score   support

           0       0.87      0.99      0.93    110375
           1       0.83      0.33      0.47     23358

    accuracy                           0.87    133733
   macro avg       0.85      0.66      0.70    133733
weighted avg       0.87      0.87      0.85    133733

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
xg_model = RandomizedSearchCV(
    (knn_model) , {
        'n_estimators' : [100,200,300,400,500,600],
        'learning_rate' : [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1],
        'max_depth' : [3,4,5,6,7,8,9,10,11,12],
        'random_state' : [42],
        'objective' : ['binary:logistic'],
        'eval_metric' : ['logloss']
    } , n_iter=10 , cv=5 , return_train_score= False
)

In [ ]:
xg_model.fit(x,y)

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=True,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_const...
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=100, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   param_distributions={'eval_metric': ['logloss'],
                                        'learning_rate': [0.1, 0.2, 0.3, 0.4,
                                                          0.5, 0.6, 0.7, 0.8,
                                                          0.9, 1],
                                        'max_depth': [3, 4, 5, 6, 7, 8, 9, 10,
                                                      11, 12],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600],
                                        'objective': ['binary:logistic'],
                                        'random_state': [42]})

In [ ]:
xg_frme = pd.DataFrame(xg_model.cv_results_)

In [ ]:
xg_frme[["mean_test_score","param_n_estimators","param_max_depth"]]

   mean_test_score  param_n_estimators  param_max_depth
0         0.888608                 600               11
1         0.890855                 500                7
2         0.898306                 400                3
3         0.888699                 200                9
4         0.897914                 200                6
5         0.888567                 500                7
6         0.885809                 200                9
7         0.888642                 500                6
8         0.895361                 400                4
9         0.893287                 300                5

In [ ]:
xg_model.best_params_

{'random_state': 42,
 'objective': 'binary:logistic',
 'n_estimators': 400,
 'max_depth': 3,
 'learning_rate': 0.1,
 'eval_metric': 'logloss'}

In [ ]:
xgb_model_best = XGBClassifier(n_estimators=400 , learning_rate=0.1 , max_depth=3 , random_state=42 , objective='binary:logistic' , eval_metric='logloss')

In [ ]:
xgb_model_best.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=400, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
xgb_model_best_pred = xgb_model_best.predict(x_test)
print(classification_report(y_test,xgb_model_best_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94    108657
           1       0.72      0.66      0.69     23084

    accuracy                           0.90    131741
   macro avg       0.83      0.80      0.81    131741
weighted avg       0.89      0.90      0.89    131741

In [ ]:
import pandas as pd
import numpy as np

# 1. Load the test set
test_df = pd.read_csv('/content/test.csv')

# Keep track of the 'id' column for the final submission
submission = pd.DataFrame({'id': test_df['id']})

# 2. Replicate all preprocessing steps applied to the training data
# Encode Gender
test_df = pd.get_dummies(test_df, columns=['Gender'], drop_first=True)
test_df['Gender_Male'] = test_df['Gender_Male'].astype(int)
test_df['Gender_Other'] = test_df['Gender_Other'].astype(int)

# Map Home_Charging_Possible and Subsidy_Available to binary integers
test_df.loc[test_df['Home_Charging_Possible'] == 'Yes', 'Home_Charging_Possible'] = 1
test_df.loc[test_df['Home_Charging_Possible'] == 'No', 'Home_Charging_Possible'] = 0
test_df['Home_Charging_Possible'] = test_df['Home_Charging_Possible'].astype(int)

test_df.loc[test_df['Subsidy_Available'] == 'Yes', 'Subsidy_Available'] = 1
test_df.loc[test_df['Subsidy_Available'] == 'No', 'Subsidy_Available'] = 0
test_df['Subsidy_Available'] = test_df['Subsidy_Available'].astype(int)

# Map Range_Anxiety_Level
test_df.loc[test_df['Range_Anxiety_Level'] == 'Low', 'Range_Anxiety_Level'] = 0
test_df.loc[test_df['Range_Anxiety_Level'] == 'Medium', 'Range_Anxiety_Level'] = 1
test_df.loc[test_df['Range_Anxiety_Level'] == 'High', 'Range_Anxiety_Level'] = 2
test_df['Range_Anxiety_Level'] = test_df['Range_Anxiety_Level'].astype(int)

# Encode categorical variables
test_df = pd.get_dummies(test_df, columns=['Current_Car_Type'], drop_first=True)
test_df = pd.get_dummies(test_df, columns=['City_Type'], drop_first=True)

test_df['Current_Car_Type_SUV'] = test_df['Current_Car_Type_SUV'].astype(int)
test_df['Current_Car_Type_Sedan'] = test_df['Current_Car_Type_Sedan'].astype(int)
test_df['Current_Car_Type_Truck'] = test_df['Current_Car_Type_Truck'].astype(int)
test_df['City_Type_Suburban'] = test_df['City_Type_Suburban'].astype(int)
test_df['City_Type_Urban'] = test_df['City_Type_Urban'].astype(int)

# 3. Apply the fitted scaler to the numerical features (bypassing name check with .values)
test_df['Age'] = scaler.transform(test_df[['Age']].values)
test_df['Annual_Income_USD'] = scaler.transform(test_df[['Annual_Income_USD']].values)
test_df['Daily_Commute_km'] = scaler.transform(test_df[['Daily_Commute_km']].values)
test_df['Number_of_Cars_Owned'] = scaler.transform(test_df[['Number_of_Cars_Owned']].values)
test_df['Charging_Stations_Near_Home'] = scaler.transform(test_df[['Charging_Stations_Near_Home']].values)
test_df['Charging_Stations_Near_Work'] = scaler.transform(test_df[['Charging_Stations_Near_Work']].values)

# Align columns with training features (drop ID and target variable if present)
x_test_final = test_df[x.columns]

# 4. Generate predictions using the best XGBoost model - now predicting probabilities
test_preds_proba = xgb_model_best.predict_proba(x_test_final)[:, 1] # Get probability of the positive class (1)

# Assign probabilities to the 'Will_Buy_EV' column
submission['Will_Buy_EV'] = test_preds_proba

# 5. Save the final submission
submission.to_csv('submission.csv', index=False)
print("Submission successfully saved to submission.csv")
display(submission.head())

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Submission successfully saved to submission.csv

       id  Will_Buy_EV
0  668665     0.009413
1  668666     0.035192
2  668667     0.037539
3  668668     0.040638
4  668669     0.051948

In [ ]:
sample_submission_df = pd.read_csv('/content/sample_submission.csv')
display(sample_submission_df.head())

       id  Will_Buy_EV
0  668665     0.174645
1  668666     0.174645
2  668667     0.174645
3  668668     0.174645
4  668669     0.174645